### ISSUE TITLE
issue: dataset.json() not work

### ISSUE THREAD

**Issue by danielhjz** [baidubce/bce-qianfan-sdk#100]
### Issue you'd like to raise.

`ds.schema()` 、`ds.json()` ，`ds.validate()`等报错
This may casued by the uncompatibility with `pydantic`.
<img width="1101" alt="4bb12adfcf6b8e0172e2e41bb4ac69f3" src="https://github.com/baidubce/bce-qianfan-sdk/assets/5894042/ef1f3dd4-58ca-4015-831d-391ec1728901">

**Comment by Dobiichi-Origami** [comment]
现在 Dataset 中集成的类均派生自 Pydantic 的 `BaseModel` 类（ `Schema` 由于函数重名而除外）。使用 `BaseModel` 可以为日常的开发节省相当一部分编写 `__init__` 函数和字段值校验逻辑的精力，并且在特定场景下提供额外功能（如 `FileDataSource` 中的 `FormatType` 推断与校验）。

但这样子做的副作用就是会继承一系列来自 `BaseModel` 的函数，并且这些函数不一定可以正常工作。以截图的报错为例，该错误是 `Table` 内集成的 `pyarrow.Table` 无法被序列化导致的。

如果要彻底解决此类问题，显而易见的有两类途径：
1. 剔除 `BaseModel`
2. 手动重写并覆盖掉自 `BaseModel` 中继承的方法
