### ISSUE TITLE
pydantic 2.5.2 不兼容

### ISSUE THREAD

**Issue by Dobiichi-Origami** [baidubce/bce-qianfan-sdk#102]
### System Info

在安装 pydantic 2.5.2 之后，mypy 提示兼容性问题
<img width="1480" alt="6b5b183fe82e6aad8217e80acee5f934" src="https://github.com/baidubce/bce-qianfan-sdk/assets/56953648/7d0ee21c-4b98-42d6-bbcd-a29001e23c61">

### Reproduction

在命令行执行 make lint

**Comment by ZingLix** [comment]
好像是langchain把包移到了langchain_core里的问题，试了下这样就不报错了

https://github.com/baidubce/bce-qianfan-sdk/pull/96/commits/2197f3568f22d364d1c0b6e5c75e3a1922553cda#diff-9511a8ab823633063395a7f4b837ac1de09c421220493fd31703055b5fc3ce2eL35-R47

**Comment by Dobiichi-Origami** [comment]
> 好像是langchain把包移到了langchain_core里的问题，试了下这样就不报错了
> 
> [2197f35#diff-9511a8ab823633063395a7f4b837ac1de09c421220493fd31703055b5fc3ce2eL35-R47](https://github.com/baidubce/bce-qianfan-sdk/commit/2197f3568f22d364d1c0b6e5c75e3a1922553cda#diff-9511a8ab823633063395a7f4b837ac1de09c421220493fd31703055b5fc3ce2eL35-R47)

修复见 PR #104
