### ISSUE TITLE
release 0.2.4

### ISSUE THREAD

**Issue by Dobiichi-Origami** [baidubce/bce-qianfan-sdk#137]
# Evaluation
- Evaluation 基础框架上线
- 支持从框架发起千帆平台评估

# Dataset
- 加入 `test_using_llm` 方法，允许用户直接在特定数据集上使用 `Model` 或者 `Service` 对象运行
- 支持异步清洗

# Model & Service
- 添加 `batch_inference` 方法

# Trainer
- 支持ERNIE-Bot-turbor-0922，0516即将下线

# resource 
- 加入请求Latency 统计, ChatCompletion、Completion stream增加首Token 时延
- Plugin增加一言插件支持（eChart、ChatFile、ImageAI）
- ebturbo新增tool、tool_choice 用于触发工具增强，EB3.5 4.0新增tool_choice
- 新增Yi_34B_Chat 预置ChatCompletion 服务

# Tool
- 转换 from Langchain to Tool

# cookbook
- 增加finetune数据多轮对话样例
- 批量推理

**Comment by danielhjz** [comment]
[ChangeHistory](https://github.com/baidubce/bce-qianfan-sdk/releases/tag/0.2.4)
