### ISSUE TITLE
Plugin query parameter type should be QfMessages instead of QfResponse 

### ISSUE THREAD

**Issue by headingy** [baidubce/bce-qianfan-sdk#228]
https://github.com/baidubce/bce-qianfan-sdk/blob/bffb2c9a84da5a8d4b2f9296c0e205b44d58e7d2/src/qianfan/resources/llm/plugin.py#L155

Hope it is clear enough. Or am I wrong?

**Comment by danielhjz** [comment]
> https://github.com/baidubce/bce-qianfan-sdk/blob/bffb2c9a84da5a8d4b2f9296c0e205b44d58e7d2/src/qianfan/resources/llm/plugin.py#L155
> 
> Hope it is clear enough. Or am I wrong?

Thank you for raising the issue! @headingy 
It should be `QfMessages`
Thank you for raising the issue! We appreciate your input. In addition, we wanted to let you know that we actively encourage community contributions. If you have the time and interest, we'd love for you to consider submitting a pull request with your proposed changes to address the reported issue.

**Comment by headingy** [comment]
This is a easy one: https://github.com/baidubce/bce-qianfan-sdk/pull/232

**Comment by headingy** [comment]
BTW

1. the [knowledge base api doc](https://cloud.baidu.com/doc/WENXINWORKSHOP/s/Blmygz6t6) says it supports `history` parameter besides `query`, but I don't see it supported in Plugin code. Will it be supported anytime soon?
2. the Plugin source code shows plugin like `eChart`. Is it publicly available? If yes, where is the documentation?


Thanks & Regards

**Comment by danielhjz** [comment]
> BTW
> 
> 1. the [knowledge base api doc](https://cloud.baidu.com/doc/WENXINWORKSHOP/s/Blmygz6t6) says it supports `history` parameter besides `query`, but I don't see it implemented in Plugin code. Will it be supported anytime soon?
> 2. the Plugin source code shows plugin like `eChart`. Is it publicly available? If yes, where is the documentation?
> 
> Thanks & Regards

1. For `qianfan.Plugin`, `history` is not an explicit fields right now. but you may be able to call like that:
```
p.do(query="query_text",
     plugins=["uuid-zhishiku"],
     history=[{"role":"user", "content":"history_query1"}, {"role":"assistant", "content":"history_response"}])
```
2. Plugin `eChart` is an not public plugin yet now, but you may be able to use by applying here:  https://console.bce.baidu.com/ticket/#/ticket/create?productId=279&questionId=1546&createDirectly=1
