### ISSUE TITLE
python-dotenv version

### ISSUE THREAD

**Issue by better629** [baidubce/bce-qianfan-sdk#270]
### Feature request

can we reduce version requirement of `python-dotenv` like `python-dotenv = ">=1.0.0"`. It seems that current is old and explicit usage of `dotenv`.

it seems the new version(1.0.0) is totally compatible with the old one.
```
[1.0.0](https://github.com/theskumar/python-dotenv/compare/v0.21.0...v1.0.0) - 2023-02-24
Fixed

Drop support for python 3.7, add python 3.12-dev (#449 by [@theskumar](https://github.com/theskumar))
Handle situations where the cwd does not exist. (#446 by [@jctanner](https://github.com/jctanner))
[0.21.1](https://github.com/theskumar/python-dotenv/compare/v0.21.0...v0.21.1) - 2023-01-21
```

**Comment by better629** [comment]
If it's possible, can you publish a new python sdk pypi version with newer `python-dotenv`?

**Comment by danielhjz** [comment]
> If it's possible, can you publish a new python sdk pypi version with newer `python-dotenv`?

`python-dotenv>=1.0.0` seems to be not compatible with `python3.7`, we will upgrade it to `dotenv>=1.0.0` in `python>=3.8`.
