### ISSUE TITLE
termux环境下pip安装qianfan失败

### ISSUE THREAD

**Issue by MonkiFantasy** [baidubce/bce-qianfan-sdk#308]
### System Info

SystemVersion:Android14
PythonVersion:3.11.6
TermuxVersion:0.118.0

### Reproduction

pip install qianfan
下面是日志
[errorlog.txt](https://github.com/baidubce/bce-qianfan-sdk/files/14470788/errorlog.txt)

**Comment by Dobiichi-Origami** [comment]
千帆 Python SDK 目前底层强依赖 Numpy 所提供的功能，且已知 Numpy 在 Termux 所模拟出来的残血 GNU 环境上无法通过编译。如果需要安装千帆 SDK，需要自行通过其他方式补全环境，如：在 Termux 上模拟一个 Ubuntu 并且在 Ubuntu 环境上进行安装。
BTW，能否麻烦告知下在安卓设备上用 Termux 安装千帆 SDK 所期望使用的功能场景是？

**Comment by ZingLix** [comment]
termux 编译环境过于麻烦，numpy等一些依赖无法通过pip安装，不建议在 termux 上使用

如果确实有需求，那么需要用 termux 提供的 pkg 安装部分依赖

```
pkg install python-numpy
pkg install libarrow-python
pkg install rust 
pkg install binutils
```

之后再通过 pip 安装千帆 sdk

```
pip install qianfan
```
