### ISSUE TITLE
千帆 langchain  特性工具支持 

### ISSUE THREAD

**Issue by dessun888** [baidubce/bce-qianfan-sdk#312]
### Feature request

langchain                0.1.10
langchain-cli            0.0.21
langchain-community      0.0.25
langchain-core           0.1.28
langchain-text-splitters 0.0.1
langserve                0.0.46
langsmith                0.1.19

已经调整 _merge.py 

### contribution or solutions

def get_agent( model = None ):

    tools          = [multiply, add, exponentiate]
    prompt         = PromptTemplate.from_template(default_agent_prompt) 
    #prompt         = prompt.partial(="")
    agent          = create_openai_tools_agent(model, tools, prompt)

    agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)

    return agent_executor  

 agent_executor = get_agent(model)
            content = agent_executor.invoke(
                {
                    "input": "Take 3 to the fifth power , 请推测其使用的方法（multiply,add,exponentiate) 给出 first_int ,second_int，exponentiate ），调用langchain工具 计算结果,Without explanation or further clarification ",
                    "chat_history":""
                }
            )

Take 3 to the fifth power , 请推测其使用的方法（multiply,add,exponentiate) 给出 first_int ,second_int，exponentiate ），调用langchain工具 计算结果,Without explanation or further clarification ', 'chat_history': '', 'output': '根据你给出的信息，这个句子“Take 3 to the fifth power”看起来像是一个需要被计算的问题。从句子中可以推断出，你可能需要将3的5次方进行计算。这个问题涉及到数学运算中的乘方，即指数运算。\n\n如果我们将数字3作为底数，将5作为指数，那么3的5次方就可以通过数学运算法则得到结果：\n\n`3^5 = 3 * 3 * 3 * 3 * 3 = 243`\n\n在你的问题中，“first_int”, “second_int”, 和 “exponentiate”可能是指在进行乘方运算时需要使用的参数。因此，你需要在“langchain”这个工具中将这些参数作为输入进行计算。\n\n如果你需要进一步的帮助，例如如何使用“langchain”工具或者如何解释这个计算过程，请提供更多的信息或者详细描述你的问题。

千帆不支持langchain 工具链，这个能解决么

**Comment by dessun888** [comment]
或者如何让千帆支持langchain 工具呢 ？ 有什么prompts

**Comment by Dobiichi-Origami** [comment]
> 或者如何让千帆支持langchain 工具呢 ？ 有什么prompts

千帆 SDK 内的 `extensions/langchian` 包提供了针对 Langchain 封装的 Agent 对象。可以尝试使用一下
