### ISSUE TITLE
partially initialized module 'qianfan' has no attribute 'ChatCompletion' (most likely due to a circular import)

### ISSUE THREAD

**Issue by wolfherder** [baidubce/bce-qianfan-sdk#421]
import os
import qianfan

os.environ["QIANFAN_ACCESS_KEY"]="--"
os.environ["QIANFAN_SECRET_KEY"]="--"

chat_comp = qianfan.ChatCompletion()
resp = chat_comp.do(endpoint="your_custom_endpoint", messages=[{
    "role": "user",
    "content": "你好"
}])

partially initialized module 'qianfan' has no attribute 'ChatCompletion' (most likely due to a circular import)

**Comment by ZingLix** [comment]
看看是不是这个代码文件的文件名是`qianfan.py`，可能和 `qianfan` 包名冲突了所以失败了

**Comment by AInseven** [comment]
是的，谢谢
