### ISSUE TITLE
Error: Path not found，ERNIE-4.0-8K

### ISSUE THREAD

**Issue by lqomg** [baidubce/bce-qianfan-sdk#424]
### System Info

nodejs @baiducloud/qianfan@0.0.6

### Reproduction

chat会话，使用ERNIE-4.0-8K模型提示路径找不到？

![image](https://github.com/baidubce/bce-qianfan-sdk/assets/29908531/5245a395-d012-49b7-abb8-42537f975e7c)

**Comment by wangting829** [comment]
你好，我们0.0.8版本才更新模型，建议升级版本～，或者直接用endpoint，  '/chat/completions_pro'

**Comment by wangting829** [comment]
0.0.6有个流式问题，麻烦升级下最新版本哈～
