### ISSUE TITLE
Issue: should be compatible with pydantic v2

### ISSUE THREAD

**Issue by CNSeniorious000** [baidubce/bce-qianfan-sdk#43]
### Issue you'd like to raise.

It prevents me from updating qianfan to >=v0.1 that you claim in pyproject.toml that this package only works with pydantic v1.

However, it turns out that only the src/qianfan/extensions/langchain/agents/baidu_qianfan_endpoint.py file directly uses pydantic's old APIs, and the entire package is unrelated to pydantic.

### Suggestion:

I am making a PR that uses pydantic.v1 if pydantic.VERSION == "2.x". It passes all the existing tests. I hope this can be of some assistance.

**Comment by danielhjz** [comment]
FYI  @CNSeniorious000  [qianfan0.1.2](https://github.com/baidubce/bce-qianfan-sdk/releases/tag/0.1.2) has been released
