### ISSUE TITLE
No module named 'qianfan' 

### ISSUE THREAD

**Issue by lijia2010114105** [baidubce/bce-qianfan-sdk#438]
### System Info

no

### Reproduction

明明安装了qianfan，确一直报错。但是运行又可以。现在的问题是无法自动提示。为啥会提示找不到了
<img width="1286" alt="image" src="https://github.com/baidubce/bce-qianfan-sdk/assets/10704765/a59c910a-6dad-45fc-867c-2656587f2f1a">

**Comment by yaogang2060** [comment]
这不是qianfan的问题。VS Code右下角看一波？切到你的 qianf 环境。
![image](https://github.com/baidubce/bce-qianfan-sdk/assets/12131589/ed7e27dd-5c74-4163-bd39-debd21ce9eac)

**Comment by lijia2010114105** [comment]
感谢大佬，确实是这个问题，我修改后就好了
