### ISSUE TITLE
chatBuilder.executeStream(); JAVA发起流式请求 

### ISSUE THREAD

**Issue by mayiyahei1992** [baidubce/bce-qianfan-sdk#455]
### Issue you'd like to raise.

JAVA发起流式请求  接口是否是一次性全部返回 Iterator<ChatResponse>？ 如果不是 我怎么提前终止他生成  这部分的 tokens怎么计算

**Comment by Azure99** [comment]
目前暂时不支持手动终止，不过可以考虑使用`stop`传入停止词，当输出遇到停止词时，会终止生成（后续不计费）

**Comment by zfhlm** [comment]
你好，我有个疑惑，SSE Iterator 是阻塞的，后面考虑变异步吗

**Comment by Azure99** [comment]
@zfhlm 您好，目前暂不支持，但未来有计划支持async。
