### ISSUE TITLE
context in chat.Stream not working.

### ISSUE THREAD

**Issue by suutaku** [baidubce/bce-qianfan-sdk#464]
### System Info

```shell
Apple Silicon m2 
OSX 14.2 
Go version go1.21.5 darwin/arm64
```

The first parameter in `chat.Stream` seems not used so i cannot figure out how to stop current chat stream.

### Reproduction

1. create a chat stream with `context` and `cancel` func.
2. run `cancel` 
3. with dig deeper, i found  `func (c *ChatCompletion) Stream(ctx context.Context, request *ChatCompletionRequest) (*ModelResponseStream, error)` not using `ctx `at all.

**Comment by ZingLix** [comment]
We've added support for context in version 0.0.4. We recommend updating to this version and giving it a try. 

If you encounter any issues, feel free to reopen the issue.
