### ISSUE TITLE
流式对话异常 NoSuchElementException

### ISSUE THREAD

**Issue by jackdeng1202** [baidubce/bce-qianfan-sdk#471]
### System Info

1. qianfan version -0.0.2 
2. System Version -java8 -android 9.0
3. language - kotlin

### Reproduction

1.   implementation "com.baidubce:qianfan:0.0.2"
2.   call api:
                
               val iterator = qianfan.chatCompletion()
                        .model("ERNIE-Bot-4") 
                        .temperature(0.7)
                        .addMessage("user", "hello")
                        .executeStream()
                while (iterator.hasNext()) {
                    var chunk = iterator.next()
                    Log.i(TAG, "result: " + chunk)
                }

3.  See error:

	   java.util.NoSuchElementException
		at com.baidubce.qianfan.util.http.SSEWrapper$1.next(SSEWrapper.java:59)
		at com.baidubce.qianfan.util.http.SSEWrapper$1.next(SSEWrapper.java:30)
		at com.baidubce.qianfan.QianfanClient$StreamIterator.next(QianfanClient.java:118)

**Comment by Azure99** [comment]
请先更新到0.0.4版本，然后使用非流式发起请求，检查下报错
