### ISSUE TITLE
千帆最新版本的python包  一个model名映射的api错误

### ISSUE THREAD

**Issue by alexC-nonsense4k** [baidubce/bce-qianfan-sdk#493]
### System Info

千帆version：0.3.10
python：3.11.0

### Reproduction

```
pip install -U qianfan 安装最新的python包
```
进入chat_completion,可发现以下错误。
![2FBD395B-7F74-4E24-BA6B-A3DAAE04D0C3](https://github.com/baidubce/bce-qianfan-sdk/assets/81558325/1468cac2-c5a8-4474-bf0b-e80362d0cb90)
正确的api是"/chat/ernie-func-8k"

**Comment by danielhjz** [comment]
收到，感谢反馈
