### ISSUE TITLE
Java网络代理配置功能

### ISSUE THREAD

**Issue by lihongjia-sinosoft** [baidubce/bce-qianfan-sdk#496]
### Feature request

在安全管理相对严格的企业实际生产环境中，可能需要通过代理访问接口，同时在很多情况下，Java项目无法通过启动设置进行网络代理访问。增加网络代理配置功能可以解决这一痛点。

### contribution or solutions

lihongjia-sinosoft:Qianfan-with-HTTP-Proxy：[java](https://github.com/baidubce/bce-qianfan-sdk/pull/495)

**Comment by Azure99** [comment]
Review有一些小问题，可以先重构下，如果着急的话可以先编译您修改后的使用。我们五月内会增加对应能力。

**Comment by lihongjia-sinosoft** [comment]
> Review有一些小问题，可以先重构下，如果着急的话可以先编译您修改后的使用。我们五月内会增加对应能力。

好的，感谢回复。

**Comment by Azure99** [comment]
您好，0.0.6版本已支持网络代理，可以通过代码或环境变量设置https.proxyHost、https.proxyPort实现。
```
System.setProperty("https.proxyHost", "127.0.0.1");
System.setProperty("https.proxyPort", "7890");
```
