### ISSUE TITLE
[JAVA SDK] Auth failed with error: {"error":"invalid_client","error_description":"unknown client id"}

### ISSUE THREAD

**Issue by sunpeng981712364** [baidubce/bce-qianfan-sdk#501]
### Issue you'd like to raise.
JAVA SDK 版本号

        <dependency>
            <groupId>com.baidubce</groupId>
            <artifactId>qianfan</artifactId>
            <version>0.0.4</version>
        </dependency>

        ChatBuilder chatBuilder = new Qianfan(Auth.TYPE_OAUTH, "", "").chatCompletion().model(modelName);
        for (MMessage message : this.messages) {
            chatBuilder = chatBuilder.addMessage(message.getRole(), message.getContent());
        }
        ChatResponse response = chatBuilder.temperature(0.7).execute(); // 发起请求
        System.out.println(response.getResult());

: Cookie rejected [BAIDUID="23AAEAA93B85ECFF24E013F37:FG=1", domain:baidu.com, path:/, expiry:Mon May 05 17:57:27 CST 2092] Illegal 'domain' attribute "baidu.com". Domain of origin: "aip.baidubce.com"
  INFO 38732 --- [nio-8020-exec-3]    : Auth failed with error: {"error":"invalid_client","error_description":"unknown client id"}

**Comment by sunpeng981712364** [comment]
求助

**Comment by Azure99** [comment]
请检查传入的`QIANFAN_AK`和`QIANFAN_SK`是否正确。
注意，如果使用`Auth.TYPE_OAUTH`来鉴权，传入的API Key和Secret Key需要在`应用接入`获取。
参考链接：https://cloud.baidu.com/doc/WENXINWORKSHOP/s/Slkkydake
