### ISSUE TITLE
java sdk ChatResponse getFlag返回Integer, 默认返回null，而不是0

### ISSUE THREAD

**Issue by cjwang666** [baidubce/bce-qianfan-sdk#508]
### System Info

Java sdk 0.0.4

### Reproduction

1. 正常调用chat功能，
2. 检查返回的flag ，ChatResponse getFlag。如果这个时候，使用flag.toString()，会抛出空指针错误。

**Comment by Dobiichi-Origami** [comment]
@Azure99 TAL

**Comment by Azure99** [comment]
这个的官方文档有些问题，后面会修正，可以按照下面的方式判断：
如果没有异常，返回null；当出现错误时才返回非null
