### ISSUE TITLE
qianfan的版本依赖冲突

### ISSUE THREAD

**Issue by joeylin** [baidubce/bce-qianfan-sdk#56]
### System Info

- qianfan version: 0.1.2
- python version: 3.10.0

### Reproduction

qianfan使用的pydantic版本跟其他的依赖包冲突

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastapi 0.96.1 requires pydantic!=1.8,!=1.8.1,<2.0.0,>=1.7.4, but you have pydantic 2.4.2 which is incompatible.
chromadb-client 0.4.16.dev0 requires pydantic<2.0,>=1.9, but you have pydantic 2.4.2 which is incompatible.

**Comment by Dobiichi-Origami** [comment]
抱歉产生这样的问题，千帆 Python SDK 的功能依赖于 Pydantic V2 的功能支持。如果你的项目有依赖 Pydantic V1 的外部依赖，请及时升级，其中：
fastapi 最新版本已经提供了对 Pydantic V2 的支持
chromadb-client 不支持 Pydantic V2，请考虑使用 chromadb，其已经支持 Pydantic V2。如果是有外部库依赖 chromadb-client，请考虑更换外部依赖。
