### ISSUE TITLE
Qianfan does not work in a NoneBot plugin

### ISSUE THREAD

**Issue by StarsetNight** [baidubce/bce-qianfan-sdk#575]
### System Info

**Qianfan Version**
- Qianfan Version: 0.3.14
**System Version**
- Python Version: 3.10.12
- Operating System: Linux 5.16.17-sun50iw9 #3.0.6 SMP Tue Aug 9 13:51:16 CST 2022 aarch64 aarch64 aarch64 GNU/Linux

### Reproduction

1. Install `qianfan`, `nonebot` and then establish a NoneBot project.
2. Make a plugin that imports qianfan.
3. See error.

**Expected behavior**
See `<time> [SUCCESS] nonebot | Succeeded to load plugin "<plugin_name>" from "<package_name>"`.

**Additional context**
I will provide my personal project if neccessary.

**Comment by Dobiichi-Origami** [comment]
1. 本项目和 Nonebot 无关，请在这里提出 Qianfan 相关的问题
2. 如果确认是 Qianfan 的问题，请提供第三步的错误信息

**Comment by StarsetNight** [comment]
> 1. 本项目和 Nonebot 无关，请在这里提出 Qianfan 相关的问题
> 2. 如果确认是 Qianfan 的问题，请提供第三步的错误信息

I have ensured the problem is from Qianfan, since the error message will occur if this library is loaded. Unfortunately, there is only one message that noticed the plugin which imported `qianfan` was failed to load. By speculation, Qianfan's code is likely to have hindered the operation of NoneBot's plug-in in terms of performance.
For more information, see error:

```shell
06-03 20:54:04 [SUCCESS] nonebot | Succeeded to load plugin "lihong_plugin_qianfan" from "reimei_plugins.lihong_plugin_qianfan"
06-03 20:54:06 [ERROR] nonebot | Failed to import "lihong_plugin_registration"
Traceback (most recent call last):
  File "/server/lihongbot/bot.py", line 29, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "/server/bot/ReimeiBot/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 125, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/server/bot/ReimeiBot/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 62, in load_all_plugins
    return manager.load_all_plugins()
  File "/server/bot/ReimeiBot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 175, in load_all_plugi
ns
    return set(
  File "/server/bot/ReimeiBot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 176, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/server/bot/ReimeiBot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 154, in load_plugin
    raise RuntimeError(
RuntimeError: Module reimei_plugins.lihong_plugin_registration is not loaded as a plugin! Make sure not to import it before loading.
```
In addition, if this problem will be surely not fixed, please give me a clear response and close this issue. Appreciation for your work.

**Comment by yanyongyu** [comment]
你的报错看上去是NoneBot相关的问题，你在加载 `lihong_plugin_registration` 插件前通过其他模块导入了他导致失败

**Comment by Dobiichi-Origami** [comment]
> > 1. 本项目和 Nonebot 无关，请在这里提出 Qianfan 相关的问题
> > 2. 如果确认是 Qianfan 的问题，请提供第三步的错误信息
> 
> I have ensured the problem is from Qianfan, since the error message will occur if this library is loaded. Unfortunately, there is only one message that noticed the plugin which imported `qianfan` was failed to load. By speculation, Qianfan's code is likely to have hindered the operation of NoneBot's plug-in in terms of performance. For more information, see error:
> 
> ```shell
> 06-03 20:54:04 [SUCCESS] nonebot | Succeeded to load plugin "lihong_plugin_qianfan" from "reimei_plugins.lihong_plugin_qianfan"
> 06-03 20:54:06 [ERROR] nonebot | Failed to import "lihong_plugin_registration"
> Traceback (most recent call last):
>   File "/server/lihongbot/bot.py", line 29, in <module>
>     nonebot.load_from_toml("pyproject.toml")
>   File "/server/bot/ReimeiBot/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 125, in load_from_toml
>     return load_all_plugins(plugins, plugin_dirs)
>   File "/server/bot/ReimeiBot/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 62, in load_all_plugins
>     return manager.load_all_plugins()
>   File "/server/bot/ReimeiBot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 175, in load_all_plugi
> ns
>     return set(
>   File "/server/bot/ReimeiBot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 176, in <genexpr>
>     filter(None, (self.load_plugin(name) for name in self.available_plugins))
> > File "/server/bot/ReimeiBot/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 154, in load_plugin
>     raise RuntimeError(
> RuntimeError: Module reimei_plugins.lihong_plugin_registration is not loaded as a plugin! Make sure not to import it before loading.
> ```
> 
> In addition, if this problem will be surely not fixed, please give me a clear response and close this issue. Appreciation for your work.

从报错来看，你的问题与 Nonebot 或者 Qianfan 两个项目本身无关，更有可能是项目本身存在的问题，建议将这个问题转到 [Nonebot Discussion](https://github.com/orgs/nonebot/discussions/)

**Comment by StarsetNight** [comment]
好的，我将会先检查自己代码的自身问题，如确无问题，我会将其发表至NoneBot Discussion。此议题我将暂时关闭，再次感谢你们的工作。
