### ISSUE TITLE
有计划支持其它语言吗？比如C++

### ISSUE THREAD

**Issue by wwqiu** [baidubce/bce-qianfan-sdk#584]
如题

**Comment by Dobiichi-Origami** [comment]
抱歉，但是我们暂时没有支持其它语言的计划，包括 CPP。
但是如果你有兴趣的话，欢迎你提供其他语言的代码。

**Comment by danielhjz** [comment]
另一种可能方案是使用例如[openai cpp](https://github.com/olrea/openai-cpp) 等开源 CPP SDK结合 千帆SDK提供的命令行工具：openai API Adapter `qianfan openai` 以快速使用

**Comment by wwqiu** [comment]
> 另一种可能方案是使用例如[openai cpp](https://github.com/olrea/openai-cpp) 等开源 CPP SDK结合 千帆SDK提供的命令行工具：openai API Adapter `qianfan openai` 以快速使用

好的，我试试看
