### ISSUE TITLE
请问如何获取当前账号获取可以使用的模型列表

### ISSUE THREAD

**Issue by liuyuesheng** [baidubce/bce-qianfan-sdk#650]
### Issue you'd like to raise.

顺便问下 usage里的token是怎么计算的，怎么才5个
{
	"id": "as-rr0ysstfj1",
	"object": "chat.completion",
	"sentence_id": 1,
	"is_end": false,
	"is_truncated": false,
	"result": "，我无法预测明天是否会下雪。",
	"need_clear_history": false,
	"usage": {
		"prompt_tokens": 5,
		"completion_tokens": 0,
		"total_tokens": 5
	}
}

**Comment by liuyuesheng** [comment]
类似openai v1/models接口

**Comment by ZingLix** [comment]
`qianfan.ChatCompletion.models()` 可以获取模型列表，如果使用的是IAM鉴权的话会从平台拉取所有可用模型

对应的接口调用是

```
from qianfan.resources.console.service import Service

resp = Service.list(["chat"])
```

对应文档：https://cloud.baidu.com/doc/WENXINWORKSHOP/s/4lqoklvr1

**Comment by liuyuesheng** [comment]
> `qianfan.ChatCompletion.models()` 可以获取模型列表，如果使用的是IAM鉴权的话会从平台拉取所有可用模型
> 
> 对应的接口调用是
> 
> ```
> from qianfan.resources.console.service import Service
> 
> resp = Service.list(["chat"])
> ```
> 
> 对应文档：https://cloud.baidu.com/doc/WENXINWORKSHOP/s/4lqoklvr1

您好，这个是python的接口哈?我想请教下nodejs怎么获取

**Comment by wangting829** [comment]
您好，如果是iam鉴权的key，js 默认会调获取动态模型的接口，然后是更新模型。然后您的诉求是把获取动态模型的方法像python一样暴露出来，下个迭代可以支持哈，直接导出方法就好

**Comment by liuyuesheng** [comment]
> 您好，如果是iam鉴权的key，js 默认会调获取动态模型的接口，然后是更新模型。然后您的诉求是把获取动态模型的方法像python一样暴露出来，下个迭代可以支持哈，直接导出方法就好

感谢及时回复
需求是这样的，我想做个支持的模型列表，让用户自己选择想用那个
所以需要获取用户支持的模型列表

我看文档里有很多接口哈
但是生成认证字符串的方法对我来说太复杂了
所以才想着调用sdk，如果sdk提供**传参生成认证字符串**的方法
那很多接口，我自己根据文档调用就好哈

**Comment by liuyuesheng** [comment]
> 您好，如果是iam鉴权的key，js 默认会调获取动态模型的接口，然后是更新模型。然后您的诉求是把获取动态模型的方法像python一样暴露出来，下个迭代可以支持哈，直接导出方法就好

感谢及时回复
需求是这样的，我想做个支持的模型列表，让用户自己选择想用那个
所以需要获取用户支持的模型列表

我看文档里有很多接口哈
但是生成认证字符串的方法对我来说太复杂了
所以才想着调用sdk，如果sdk提供**传参生成认证字符串**的方法
那很多接口，我自己根据文档调用就好哈

**Comment by wangting829** [comment]
是说鉴权部分么，IAM鉴权只需要提供QIANFAN_ACCESS_KEY / QIANFAN_SECRET_KEY 哈，有提供签名方法，这期把模型列表接口暴露出来，只要认证过，就可以直接调用哈

**Comment by liuyuesheng** [comment]
> 是说鉴权部分么，IAM鉴权只需要提供QIANFAN_ACCESS_KEY / QIANFAN_SECRET_KEY 哈，有提供签名方法，这期把模型列表接口暴露出来，只要认证过，就可以直接调用哈

有提供签名方法 ,这个方法具体是哪个哈？nodejs里，
这样有些接口没有暴露的话，我可以自己看文档拼参数调用
不过确实还是ak sk直接调用sdk最方便

**Comment by wangting829** [comment]
如果需要获取动态模型，需要使用IAM的key，请求动态模型api需要先签名，sdk会提供哈
