### ISSUE TITLE
OpenAI 适配器 的 OPENAI_API_KEY 能不能成为一个 “真实” 的？

### ISSUE THREAD

**Issue by wencan** [baidubce/bce-qianfan-sdk#652]
### Feature request

https://github.com/baidubce/bce-qianfan-sdk/blob/main/cookbook/openai_adapter.ipynb

期望：客户端程序，必须提供匹配的 适配器OPENAI_API_KEY，才能访问服务。
设想下，这么一种场景：我在公网上运行openai适配器，开放端口。因为OPENAI_API_KEY可以任意填，一旦端口被发现……

**Comment by danielhjz** [comment]
收到，我们会在下一版本中考虑加入这个feature

**Comment by danielhjz** [comment]
请使用最新的千帆 SDK>=0.4.1 qianfan openai有新的命令行参数--api-key可以设定鉴权的key，并模拟openai-api bearer token带上鉴权效果 @wencan
