### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'qianfanAk')

### ISSUE THREAD

**Issue by jianjiani** [baidubce/bce-qianfan-sdk#655]
### Issue you'd like to raise.

![image](https://github.com/baidubce/bce-qianfan-sdk/assets/26543707/4a0e4df6-48a6-4c57-89ae-c683b49caac0)
升级sdk到最新的0.1.2版本后调用报错，回退到0.1.0版本可以正常使用；
node版本v20.11.1
pnpm版本用了8.3.1 和 9.1.1

**Comment by jianjiani** [comment]
![image](https://github.com/baidubce/bce-qianfan-sdk/assets/26543707/eab0fb62-ef16-47dd-9320-9b7581ec445a)
getAccessToken方法没有显式地绑定this，这样传递是不是会导致this指向发生变化呀？

**Comment by Leophen** [comment]
请问是调用哪个 API 报的错

**Comment by danielhjz** [comment]
0.1.4已修复 @jianjiani
