### ISSUE TITLE
无法初始化QianfanEmbeddingsEndpoint

### ISSUE THREAD

**Issue by martin-wan01** [baidubce/bce-qianfan-sdk#669]
### System Info

chromadb                                 0.5.4
langchain                                0.2.7
langchain-community                      0.2.7
langchain-core                           0.2.17
langchain-experimental                   0.0.17
langchain-google-genai                   1.0.5
langchain-text-splitters                 0.2.0
llama-index-llms-qianfan                 0.1.0
llama-index-utils-qianfan                0.1.0
pdfplumber                               0.11.2
qianfan                                  0.4.1.1

### Reproduction

!pip install -U langchain
!pip install -U chromadb
!pip install -U qianfan
!pip install -U pdfplumber

os.environ['QIANFAN_AK'] = "your_ak"
os.environ['QIANFAN_SK'] = "your_sk"

from langchain.embeddings import QianfanEmbeddingsEndpoint
from langchain.vectorstores import Chroma

embeddings = QianfanEmbeddingsEndpoint()

错误信息：
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
Cell In[22], line 4
      1 from langchain.embeddings import QianfanEmbeddingsEndpoint
      2 from langchain.vectorstores import Chroma
----> 4 embeddings = QianfanEmbeddingsEndpoint()
      6 #vectorstore = Chroma.from_documents(documents=all_splits, embedding=embeddings)

File ~/.pyenv/versions/3.11.4/envs/azureai/lib/python3.11/site-packages/pydantic/main.py:341, in pydantic.main.BaseModel.__init__()

ValidationError: 2 validation errors for QianfanEmbeddingsEndpoint
qianfan_ak
  str type expected (type=type_error.str)
qianfan_sk
  str type expected (type=type_error.str)

**Comment by danielhjz** [comment]
可以暂时尝试降级langchain_community解决：
```
pip install langchain_community==0.2.6
```
具体修复的方案正在推进。

**Comment by martin-wan01** [comment]
> @martin-wan01 可以暂时尝试降级langchain_community解决：
> 
> ```
> pip install langchain_community==0.2.6
> ```
> 
> 具体修复的方案正在推进langchain侧解决

好的，我稍后试试。

**Comment by martin-wan01** [comment]
> @martin-wan01 可以暂时尝试降级langchain_community解决：
> 
> ```
> pip install langchain_community==0.2.6
> ```
> 
> 具体新版修复的方案正在推进langchain侧解决

搞定了。好像两个都需要0.2.6版本才行。Thanks。

%pip install langchain==0.2.6
%pip install langchain_community==0.2.6

**Comment by Dobiichi-Origami** [comment]
[修复代码](https://github.com/langchain-ai/langchain/pull/24293)已被 langchain 合入，请注意 langchain-community 后续升级 @martin-wan01

**Comment by martin-wan01** [comment]
> [修复代码](https://github.com/langchain-ai/langchain/pull/24293)已被 langchain 合入，请注意 langchain-community 后续升级 @martin-wan01

Thanks.
