### ISSUE TITLE
Java SDK支持一下系统记忆API

### ISSUE THREAD

**Issue by xwenj** [baidubce/bce-qianfan-sdk#712]
### Issue you'd like to raise.

Java SDK系统记忆版本大概什么时候会发布

**Comment by danielhjz** [comment]
下一版本（预计本周）会支持

> ### Issue you'd like to raise.
> Java SDK系统记忆版本大概什么时候会发布
> 
> ### Suggestion:
> _No response_

**Comment by Azure99** [comment]
您好，Java SDK新版本已经发布，请更新到**0.1.0**版本后，参考以下系统记忆调用示例
https://github.com/baidubce/bce-qianfan-sdk/blob/main/java/example/src/main/java/com/baidubce/SystemMemoryExample.java
