### ISSUE TITLE
system?

### ISSUE THREAD

**Issue by yuanjie-ai** [baidubce/bce-qianfan-sdk#750]
### System Info

api return error, req_id: as-qedi6gntmw code: 336006, msg: the length of messages must be an odd number

### Reproduction

api return error, req_id: as-qedi6gntmw code: 336006, msg: the length of messages must be an odd number

**Comment by danielhjz** [comment]
千帆当前API(V1)不支持message role = system形式的传参，如果要设置system可以按照如下例子：
```python
ChatCompletion().do(system='xxx', messages=[{"role":"user","content":"xxx" }])
```

ps.后续千帆API V2会兼容system message

**Comment by yuanjie-ai** [comment]
非要重复造轮子，关键轮子还这么烂



---Original---
From: ***@***.***&gt;
Date: Tue, Aug 20, 2024 10:05 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [baidubce/bce-qianfan-sdk] system? (Issue #750)




 
千帆当前API(V1)不支持message role = system形式的传参，如果要设置system可以按照如下例子：
 ChatCompletion().do(system='xxx', messages=[{"role":"user","content":"xxx" }])
 
ps.后续千帆API V2会兼容system message
