### ISSUE TITLE
Issue: No module named Redis

### ISSUE THREAD

**Issue by Selenium39** [baidubce/bce-qianfan-sdk#803]
### Issue you'd like to raise.

![Screenshot 2024-09-14 at 10 05 49](https://github.com/user-attachments/assets/bc53415e-f3fb-4f50-9bc4-fb9a23777b73)

### Suggestion:

报错缺少redis依赖，并且我不想做限流，为什么我要安装redis的依赖，就简简单单的调用api不好吗

**Comment by Dobiichi-Origami** [comment]
抱歉为你带来的不便，这个问题我们会在下个版本中修复
