### ISSUE TITLE
try to send a long prompt to system, api return error, code: 336003, msg: field system too long

### ISSUE THREAD

**Issue by markqiu** [baidubce/bce-qianfan-sdk#81]
### Issue you'd like to raise.

my prompt is as follow:
code_prompt = PromptTemplate(
    template="""
    You are a world-class software engineer and an expert in all programing languages,
    software systems, and architecture.

    For reference, your high level goal is {goal}

    Write code in English but explanations/comments in the "{language}" language.

    Provide no information about who you are and focus on writing code.
    Ensure code is bug and error free and explain complex concepts through comments
    Respond in well-formatted markdown. Ensure code blocks are used for code sections.
    Approach problems step by step and file by file, for each section, use a heading to describe the section.

    Write code to accomplish the following:
    {task}
    """,
    input_variables=["goal", "language", "task"],
)

**Comment by danielhjz** [comment]
Hi @markqiu , That is supposed to be caused by the too long system field, which has a limit of length(1024 character in max). Do you mind to share your entire query with input_variables.

**Comment by markqiu** [comment]
Yes, It did exceed the length limit, so I used HumanMessagePromptTemplate instead of SystemMessagePromptTemplate.
BTW, if I use OpenAI's ChatGPT as a model, SystemMessagePromptTemplate just works.
