### ISSUE TITLE
人为定义 index.d.ts 让整个包类型丢失

### ISSUE THREAD

**Issue by hstarorg** [baidubce/bce-qianfan-sdk#843]
### System Info

https://github.com/baidubce/bce-qianfan-sdk/blob/main/javascript/index.d.ts

### Reproduction

自己开发的包建议自己安装起来用下！

**Comment by mondaylab** [comment]
@hstarorg 亲方便截图下具体在本地的复现情况么 以及目前遇到了什么问题 还有期待修复后的结果可以描述下哈

**Comment by ranme4ever** [comment]
![image](https://github.com/user-attachments/assets/658f8651-2b23-4e85-9473-bfe00992d396)
你们的declare module '@baiducloud/qianfan' 中没有任何类型定义，在typescript 环境下sdk用不了
