### ISSUE TITLE
[Python SDK] With qianfan==0.4.11, completion.batch_do is SUPER slow compared with 0.4.6

### ISSUE THREAD

**Issue by chenyanzz** [baidubce/bce-qianfan-sdk#855]
### System Info

qianfan 0.4.11
macos and windows reproduce

### Reproduction

code

```
qianfan.Completion(model='...')
BATCH_SIZE = 50
batch_do(['some question'] * BATCH_SIZE, worker_num=BATCH_SIZE)
```

and the traffic capture is as below, which shows:
Every llm chat request must firstly call get model list "qianfan.baidubce.com/wenxinworkshop/service/list"
and this api is sometimes very slow, and seems many of this model-list request is ahead of ALL batched LLM chat calls.

I think this is a BUG, which result in batch_do() super slow, in quanfan=0.4.11; waiting 40s firstly and then about 1qps.
and when I downgraded to quanfan==0.4.6 the batch request return back to normal concurrent-call speed, at >8qps 

<img width="566" alt="image" src="https://github.com/user-attachments/assets/1fcc2c88-97c4-4f7f-aeea-81615932c546">

**Comment by Dobiichi-Origami** [comment]
thanks for your feedback, we will take a deep look.

**Comment by Dobiichi-Origami** [comment]
We introduce a warm-up procedure before batch inferencing starting in 0.4.12. Try it and feedback if there is still any question
