### ISSUE TITLE
[BUG]对于有关联问题的多次工具调用，只能发起第一次调用，不能发起后续工具调用

### ISSUE THREAD

**Issue by kingcn** [baidubce/bce-qianfan-sdk#865]
### System Info

qianfan 0.4.11

### Reproduction

https://github.com/baidubce/bce-qianfan-sdk/blob/main/cookbook/agents/qianfan_single_action_agent_example.ipynb
在github代码示例中就存在这个问题

[sub-task1: 调用[arxiv]工具查询physics领域的论文, sub-task2: 调用[wikipedia]工具查询论文作者的百科信息]。接下来我需要调用[arxiv]工具来查询physics领域的论文。
->根据您的请求，我找到了一篇关于physics领域的论文。这篇论文的标题是“Is Physics Sick? [In Praise of Classical Physics]”，作者为Hisham Ghassib，发布于2012年9月4日。论文摘要中提到，理论物理更像一个有机体而非一个刚性的结构，现代物理在某种程度上存在病症，而经典物理则是一个健康的科学模型。\n\n关于作者的百科信息，由于Arxiv主要提供论文的搜索和查询功能，并不直接提供作者的百科信息。您可以通过搜索引擎或专门的百科网站来查找关于Hisham Ghassib的更多信息。如果您需要进一步的帮助或有其他问题，请随时告诉我。

[BUG] 并没有执行subtask2！

实际代码实测中，单次提问多个有关联的问题，需要连续发起多个子任务进行工具调用的情况下，均无法发起后续工具调用，只会发起首个子任务中的工具调用

**Comment by Dobiichi-Origami** [comment]
可以尝试一下不同版本的模型进行 Function Call，这个主要是模型效果的问题
