### ISSUE TITLE
无法找到模块“@baiducloud/qianfan”的声明文件。

### ISSUE THREAD

**Issue by 1234567845246** [baidubce/bce-qianfan-sdk#869]
### Feature request

在typesctipt中调用时无法正常引入，没有index.d.ts文件，在vscode中无法正常的调用

**Comment by mondaylab** [comment]
@1234567845246 你好 辛苦提供下使用的版本号

**Comment by 1234567845246** [comment]
> @1234567845246你好辛苦提供下使用的版本号

我是直接npm下载的0.2.0.这是报错提示，无法正常跳转
![image](https://github.com/user-attachments/assets/dc430ed2-dc53-474e-aeb4-53484f992547)
我目前的解决方法是直接在你们的packages.json中添加types字段指引到你们的index.ts
![image](https://github.com/user-attachments/assets/0d80d006-676b-464e-8399-04b6dac15f63)
这样就可以正常跳转和代码提示了
![image](https://github.com/user-attachments/assets/37c5fd23-cb3d-4041-b65f-cc5a809f9971)

**Comment by mondaylab** [comment]
@1234567845246 你好，首先非常感谢你的详细描述。目前该问题目前已修复上线到0.2.1版本，有空可以再试下哈 如有其他问题欢迎再留言
