### ISSUE TITLE
release 0.2.1

### ISSUE THREAD

**Issue by Dobiichi-Origami** [baidubce/bce-qianfan-sdk#91]
- Resources
  - 新增预置模型服务
     - [XuanYuan-70B-Chat-4bit](https://cloud.baidu.com/doc/WENXINWORKSHOP/s/Ylp88e5jc)
     - [Qianfan-Chinese-Llama-2-13B](https://cloud.baidu.com/doc/WENXINWORKSHOP/s/8lo479b4b)
     - [SQLCoder-7B](https://cloud.baidu.com/doc/WENXINWORKSHOP/s/Hlo472sa2)
     - [CodeLlama-7b-Instruct](https://cloud.baidu.com/doc/WENXINWORKSHOP/s/ylo47d03k)
  - request_Id支持
  - requestor 打印信息优化
 
- Component
  - Hub
  - Prompt 上线

- Dataset
  - 新功能：
    - Dataset 同时支持数组模式表示与 Table 模式表示
    - 新增 `Insert` 类函数与 `col_renames` 函数
    - 支持用户额外传递私有 BOS 配置，中转上传数据集到公共 BOS 数据集中
    - 支持直接从 BOS 文件创建并导入数据集
    - 自动 Group ID 压缩与重排
    - Schema 校验失败时，现提供官方格式示例地址
    - 可以使用 `len()` 方法获取 Dataset 内数据的数量
  - Bug Fix:
    - 修复了当目的文件路径不存在时导出失败的问题
    - 修复了 `col_append` 可添加相同列名新列的问题
    - 从 Table 与 Dataset 中移除了 `pydantic.BaseModel`
    - 增加了更多单测

- Trainer
  - 持续优化使用体验
     - EventHandler和Trainer绑定逻辑优化
  - 支持Model，Service

- Cookbook
  - Dataset
  - Trainer
  - Prompt

**Comment by danielhjz** [comment]
[ChagenHistory](https://github.com/baidubce/bce-qianfan-sdk/releases/tag/0.2.1)
