### ISSUE TITLE
SDK如何调用自己微调好的模型？

### ISSUE THREAD

**Issue by lielie976** [baidubce/bce-qianfan-sdk#95]
### Issue you'd like to raise.

如题，自己微调好了自己的模型，替换了自己的AK、SK和model的名字，结果报错，难道SDK只能调用预置好的模型吗？

**Comment by stonekim** [comment]
可以在发布成服务后，使用自定义API地址的endpoint 的方式来调用，例如：

```Python
# 指定自行发布的模型
resp = chat_comp.do(endpoint="your_custom_endpoint", messages=[{
    "role": "user",
    "content": "你好"
}])
```

具体可参考：
[平台使用快速开始-Step5:发布服务](https://cloud.baidu.com/doc/WENXINWORKSHOP/s/qlgujhcpo#step5%E5%8F%91%E5%B8%83%E6%9C%8D%E5%8A%A1)
[SDK推理接口](https://github.com/baidubce/bce-qianfan-sdk/blob/main/docs/inference.md)

**Comment by ChengchengDu** [comment]
如何获取自定义的endpoint
